#!/bin/bash

echo "=== Quick Demo Commands ==="
echo ""
echo "1️⃣  List S3 bucket:"
echo "   awslocal s3 ls s3://shopping-images --recursive"
echo ""
echo "2️⃣  View DynamoDB items:"
echo "   awslocal dynamodb scan --table-name tasks"
echo ""
echo "3️⃣  Check SQS messages:"
echo "   awslocal sqs receive-message --queue-url http://localhost:4566/000000000000/task-queue"
echo ""
echo "4️⃣  Test API health:"
echo "   curl http://localhost:3000/health"
echo ""
echo "5️⃣  Upload test image:"
echo "   ./scripts/test-upload.sh"
echo ""
echo "6️⃣  View service logs:"
echo "   docker-compose logs -f [service-name]"
echo ""
echo "Available services: localstack, storage-service, task-service, api-gateway"
echo ""
